spring:
  datasource:
    username: root
    password: shenwei123456
    url: jdbc:mysql://localhost:3306/zsw_chat?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
  
  # Spring Security 配置
  security:
    user:
      name: admin
      password: admin124
      roles: ADMIN

logging:
  level:
    com.example.zsw_chat_server.mapper: debug