spring:
  datasource:
    username: root
    password: shenwei123456
    url: jdbc:mysql://localhost:3306/zsw_chat?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false

logging:
  level:
    com.zsw.chat.mapper: debug